spring:
  application:
    name: DataAccessService
    
server:
  servlet:
    encoding:
      force: true
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true

info:
  app:
    name: DataAccessService

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG