spring:
  application:
    name: DataAccessService
  datasource:
    url: jdbc:h2:./demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console: 
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  servlet:
    encoding:
      force: true
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true



info:
  app:
    name: DataAccessService

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG