-- Create Tables 

CREATE TABLE [dbo].[USER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ACCOUNT] [nvarchar](16) NOT NULL,
	[PASSWORD] [nvarchar](32) NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
	[EMAIL] [nvarchar](32) NOT NULL,
	[ROLE] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLE] FOREIGN KEY([ROLE])
REFERENCES [dbo].[ROLE] ([ROLE_ID])
GO

ALTER TABLE [dbo].[USER] CHECK CONSTRAINT [FK_USER_ROLE]
GO

----

CREATE TABLE [dbo].[ROLE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
	[ROLE_ID] [nvarchar](3) NOT NULL,
	[APPROVALSTAGE] [int] NOT NULL,
 CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_ROLE] UNIQUE NONCLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--

CREATE TABLE [dbo].[REQUIREMENT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SUBJECT] [nvarchar](64) NOT NULL,
	[CONTENT] [nvarchar](max) NOT NULL,
	[REQUESTER] [nvarchar](16) NOT NULL,
	[REQUESTTIME] [datetime] NOT NULL,
	[ISAPPROVE] [bit] NOT NULL,
	[APPROVALTIME] [datetime] NULL,
 CONSTRAINT [PK_REQUIREMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[REQUIREMENT] ADD  CONSTRAINT [DF_REQUIREMENT_REQUESTTIME]  DEFAULT (getdate()) FOR [REQUESTTIME]
GO

ALTER TABLE [dbo].[REQUIREMENT]  WITH CHECK ADD  CONSTRAINT [FK_REQUIREMENT_USER] FOREIGN KEY([REQUESTER])
REFERENCES [dbo].[USER] ([ACCOUNT])
GO

ALTER TABLE [dbo].[REQUIREMENT] CHECK CONSTRAINT [FK_REQUIREMENT_USER]
GO

----

CREATE TABLE [dbo].[APPROVALRECORD](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[REQUIREMENT] [bigint] NOT NULL,
	[CURRENTSTAGE] [int] NOT NULL,
	[NEXTSTAGE] [int] NULL,
	[REQUESTER] [nvarchar](16) NOT NULL,
	[APPROVER] [nvarchar](16) NULL,
	[RECORDTIME] [datetime] NOT NULL,
 CONSTRAINT [PK_APPROVALRECORD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APPROVALRECORD] ADD  CONSTRAINT [DF_APPROVALRECORD_RECORDTIME]  DEFAULT (getdate()) FOR [RECORDTIME]
GO

ALTER TABLE [dbo].[APPROVALRECORD]  WITH CHECK ADD  CONSTRAINT [FK_APPROVALRECORD_USER] FOREIGN KEY([APPROVER])
REFERENCES [dbo].[USER] ([ACCOUNT])
GO

ALTER TABLE [dbo].[APPROVALRECORD] CHECK CONSTRAINT [FK_APPROVALRECORD_USER]
GO

ALTER TABLE [dbo].[APPROVALRECORD]  WITH CHECK ADD  CONSTRAINT [FK_APPROVALRECORD_USER1] FOREIGN KEY([REQUESTER])
REFERENCES [dbo].[USER] ([ACCOUNT])
GO

ALTER TABLE [dbo].[APPROVALRECORD] CHECK CONSTRAINT [FK_APPROVALRECORD_USER1]
GO


-- Insert initial Role
insert into ROLE (NAME, ROLE_ID, APPROVALSTAGE) values ('Requester', 'RQ', 0); -- Requirements Requester
insert into ROLE (NAME, ROLE_ID, APPROVALSTAGE) values ('Stage1Approver', 'S1A', 1); -- Requirements Stage 1 Approver
insert into ROLE (NAME, ROLE_ID, APPROVALSTAGE) values ('Stage2Approver', 'S2A', 2); -- Requirements Stage 2 Approver
insert into ROLE (NAME, ROLE_ID, APPROVALSTAGE) values ('Stage3Approver', 'S3A', 3); -- Requirements Stage 3 Approver
insert into ROLE (NAME, ROLE_ID, APPROVALSTAGE) values ('Stage4Approver', 'S4A', 4); -- Requirements Stage 4 Approver

-- Insert initial User
-- Plain password 'password' encrypted by AES, Secret Key: cg12192001@gmail
insert into [USER] (ACCOUNT, PASSWORD, NAME, EMAIL, ROLE) values ('RQ', '84BE55F4ECCC099AB896C1DC15BA6308', 'Requirements Requester', 'aa@bb.cc', 'RQ'); -- Requirements Requester
insert into [USER] (ACCOUNT, PASSWORD, NAME, EMAIL, ROLE) values ('S1A', '84BE55F4ECCC099AB896C1DC15BA6308', 'Requirements Stage 1 Approver', 'bb@bb.cc', 'S1A'); -- Requirements Stage 1 Approver
insert into [USER] (ACCOUNT, PASSWORD, NAME, EMAIL, ROLE) values ('S2A', '84BE55F4ECCC099AB896C1DC15BA6308', 'Requirements Stage 2 Approver', 'cc@bb.cc', 'S2A'); -- Requirements Stage 2 Approver
insert into [USER] (ACCOUNT, PASSWORD, NAME, EMAIL, ROLE) values ('S3A', '84BE55F4ECCC099AB896C1DC15BA6308', 'Requirements Stage 3 Approver', 'dd@bb.cc', 'S3A'); -- Requirements Stage 3 Approver
insert into [USER] (ACCOUNT, PASSWORD, NAME, EMAIL, ROLE) values ('S4A', '84BE55F4ECCC099AB896C1DC15BA6308', 'Requirements Stage 4 Approver', 'ee@bb.cc', 'S4A'); -- Requirements Stage 4 Approver



	