spring:
  application:  
    name: APIGateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': 
            allowedOrigins: 
              - '*'
            allowedHeaders:
              - '*'
            allow-credentials: true 
            allowedMethods:
              - '*'              
      discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true

server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true
    
whitelist:
  functions:
    - 
      uri: /user/login
      method: POST
      
ignorecache:
  functions:
    - 
      uri: /auth/generateToken
      method: POST

jwt:
  secret: gVxpwvWz9QprW4bKWIIryH1mycnEoiWw

## Enable following setting in production environemnt       
##management:
##  endpoints:
##    web:    
##      exposure:
##        exclude: apigateway

info:
  app:
    name: APIGateway
    requestMapping: /

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG