spring:
  application:
    name: user
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=demo
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: letmefree1219
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    
server:
  servlet:    encoding:      force: true
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true

aes:
  key: cg12192001@gmail

info:
  app:
    name: UserService
    requestMapping: /user

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG    