spring:
  datasource:
    url: jdbc:sqlserver://220.135.175.117:1433;database=oca_db
    username: sa
    password: letmefree1219
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  application:    name: user
    
server:
  servlet:    encoding:      force: true
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true

info:
  app:
    name: UserService
    requestMapping: /user

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      com.uec: DEBUG    