spring:
  application:
    name: auth
  messages:
    basename: static/i18n/messages
    
server:
  servlet:
    encoding:
      force: true
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true
  
jwt:
  secret: gVxpwvWz9QprW4bKWIIryH1mycnEoiWw

info:
  app:
    name: AuthService
    requestMapping: /auth

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG