server:
  servlet:    encoding:      force: true
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true

info:
  app:
    name: UserService
    requestMapping: /user

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG    