spring:
  application:
    name: EurekaService

server:
  port: 8081
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG
