spring:
  application:
    name: requirements

server:
  servlet:    encoding:      force: true
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true

info:
  app:
    name: RequirementsService
    requestMapping: /requirements

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG    