spring:
  application:
    name: requirements
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=demo
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: letmefree1219
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true

server:
  servlet:    encoding:      force: true
  port: 8085
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    fetchRegistry: true

info:
  app:
    name: RequirementsService
    requestMapping: /requirements

logging:
    level:
      root: ERROR
      org.springframework: ERROR
      ron.architecture: DEBUG    